version: "3.7"

services:
  kai-backend-mysql:
    image: mysql:8.0.27
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: "kai-backend"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: ""
    volumes:
      - "./kai-backend-mysql:/var/lib/mysql"
    restart: always
  kai-backend-backend:
    image: "kai-backend-backend:1.0.0"
    ports:
      - "8080:8080"
    depends_on:
      - "kai-backend-mysql"
    volumes:
      - "./kai-backend-backend:/var/www/html"
    restart: always
